# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nsbudapest-graphql' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nsbudapest-graphql
  pod 'SkeletonView'
  pod 'Emoji-swift'
  pod 'Apollo'
  pod 'UIColor_Hex_Swift', '~> 5.0.0'
end
